# This file was generated by GoReleaser. DO NOT EDIT.
cask "pidof" do
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/zerospiel/pidof/releases/download/v#{version}/pidof_#{version}_Darwin_x86_64.tar.gz"
      sha256 "75c0f2407be7c3180850e50383e2af427268ccce3fe731bca49887cd8651f580"
    end
    on_arm do
      url "https://github.com/zerospiel/pidof/releases/download/v#{version}/pidof_#{version}_Darwin_arm64.tar.gz"
      sha256 "410cc183282bb6b1500e99c0eebd9c2fc707a5596ccf8b09982a3e0058ce4fd7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zerospiel/pidof/releases/download/v#{version}/pidof_#{version}_Linux_x86_64.tar.gz"
      sha256 "de9b2f18db9de9ffb98e889fbb2ce442e1f04cc0d6abbfa234e128896b358e66"
    end
    on_arm do
      url "https://github.com/zerospiel/pidof/releases/download/v#{version}/pidof_#{version}_Linux_arm64.tar.gz"
      sha256 "38e40a5bf2a3b786fbc6eb4b5eb432ac6ee0ee6821b16a762f5f7058617979ed"
    end
  end

  name "pidof"
  desc "Display the PID number for a given process name(s)"
  homepage "https://github.com/zerospiel/pidof"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pidof"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pidof"]
    end
  end

  # No zap stanza required

end
