# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
cask "pidof" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/zerospiel/pidof/releases/download/v#{version}/pidof_#{version}_Darwin_x86_64.tar.gz"
      sha256 "b6bfe1248339deec7891b031a64d542674f9cde8b79635ced331fe275b55b9b6"
    end

    on_arm do
      url "https://github.com/zerospiel/pidof/releases/download/v#{version}/pidof_#{version}_Darwin_arm64.tar.gz"
      sha256 "13d4db70fc367431b926360a329df8e88cbcf569b22332526f6a69436dcd279d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zerospiel/pidof/releases/download/v#{version}/pidof_#{version}_Linux_x86_64.tar.gz"
      sha256 "f0f3a4976558a2edeb4bbe734e99979d4a4a179532f31fd6775abaa96a539d69"
    end

    on_arm do
      url "https://github.com/zerospiel/pidof/releases/download/v#{version}/pidof_#{version}_Linux_arm64.tar.gz"
      sha256 "4d34741f3a3ae4951ba4efe0ba3cbd7f018adacb9389b134938ec62fd8022f25"
    end
  end

  name "pidof"
  desc "Display the PID number for a given process name(s)"
  homepage "https://github.com/zerospiel/pidof"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pidof"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pidof"]
    end
  end

  # No zap stanza required
end
