# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pidof < Formula
  desc "A small cross-UNIX pidof-like CLI for UNIX (mostly macOS)"
  homepage "https://github.com/zerospiel/pidof"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zerospiel/pidof/releases/download/v0.0.1/pidof_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "66f138f75c0b611baf376f1831eb6fb007330600eb4cec1cd69754bfe086388b"

      define_method(:install) do
        bin.install "pidof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zerospiel/pidof/releases/download/v0.0.1/pidof_0.0.1_Darwin_arm64.tar.gz"
      sha256 "066025d6088e9b1d24456f03327adf535262020790cf3f2130844762bb7677f8"

      define_method(:install) do
        bin.install "pidof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zerospiel/pidof/releases/download/v0.0.1/pidof_0.0.1_Linux_x86_64.tar.gz"
      sha256 "e584ae9bcc924f8acf947a78f7c823c3765dbfad592a91d71547468b224f5509"
      define_method(:install) do
        bin.install "pidof"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zerospiel/pidof/releases/download/v0.0.1/pidof_0.0.1_Linux_arm64.tar.gz"
      sha256 "c4e2c5fd623880ea4e066f936e8ac788972a1c06315c9bd53fe2cb989029441f"
      define_method(:install) do
        bin.install "pidof"
      end
    end
  end

  test do
    assert_match "pidof", shell_output("#{bin}/pidof --version")
  end
end
