# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pidof < Formula
  desc "Display the PID number for a given process name(s)"
  homepage "https://github.com/zerospiel/pidof"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zerospiel/pidof/releases/download/v0.1.1/pidof_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "b6bfe1248339deec7891b031a64d542674f9cde8b79635ced331fe275b55b9b6"

      define_method(:install) do
        bin.install "pidof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zerospiel/pidof/releases/download/v0.1.1/pidof_0.1.1_Darwin_arm64.tar.gz"
      sha256 "13d4db70fc367431b926360a329df8e88cbcf569b22332526f6a69436dcd279d"

      define_method(:install) do
        bin.install "pidof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zerospiel/pidof/releases/download/v0.1.1/pidof_0.1.1_Linux_x86_64.tar.gz"
      sha256 "f0f3a4976558a2edeb4bbe734e99979d4a4a179532f31fd6775abaa96a539d69"
      define_method(:install) do
        bin.install "pidof"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zerospiel/pidof/releases/download/v0.1.1/pidof_0.1.1_Linux_arm64.tar.gz"
      sha256 "4d34741f3a3ae4951ba4efe0ba3cbd7f018adacb9389b134938ec62fd8022f25"
      define_method(:install) do
        bin.install "pidof"
      end
    end
  end

  test do
    assert_match "pidof", shell_output("#{bin}/pidof -v")
  end
end
