# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pidof < Formula
  desc "Display the PID number for a given process name(s). Drop-in replacement for the deprecated NightProductions pidof."
  homepage "https://github.com/zerospiel/pidof"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zerospiel/pidof/releases/download/v0.1.0/pidof_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "6a2a2807f242f87736e53b04b4d87efd477e4f1a5d30876d57ce0aea309dfae7"

      define_method(:install) do
        bin.install "pidof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zerospiel/pidof/releases/download/v0.1.0/pidof_0.1.0_Darwin_arm64.tar.gz"
      sha256 "235e5c6d5fe0c6e26e944c27b5f34983d66db77a40254b5e58f4f4421f43fbbd"

      define_method(:install) do
        bin.install "pidof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zerospiel/pidof/releases/download/v0.1.0/pidof_0.1.0_Linux_x86_64.tar.gz"
      sha256 "3ede1a4818466ad9aea43b74c3197189af5df7339ee4642b1f8ef1d4418da44a"
      define_method(:install) do
        bin.install "pidof"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zerospiel/pidof/releases/download/v0.1.0/pidof_0.1.0_Linux_arm64.tar.gz"
      sha256 "ccdcc66badcb3afecc89c16dfc2103a452e9b2208b8d031d9b2681d7e6b1f32e"
      define_method(:install) do
        bin.install "pidof"
      end
    end
  end

  test do
    assert_match "pidof", shell_output("#{bin}/pidof --version")
  end
end
